<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class BrandsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('brands')->delete();
        
        \DB::table('brands')->insert(array (
            0 => 
            array (
                'id' => 1,
                'name' => 'MITSUBISHI',
                'bn_name' => 'মিতসুবিশি',
                'country_id' => 108,
                'status' => 'Active',
                'created_by' => 2,
                'updated_by' => 2,
                'deleted_by' => NULL,
                'created_at' => '2021-09-07 18:41:37',
                'updated_at' => '2021-09-07 18:54:43',
                'deleted_at' => NULL,
            ),
            1 => 
            array (
                'id' => 2,
                'name' => 'ISUZU',
                'bn_name' => 'ইসুজু',
                'country_id' => 108,
                'status' => 'Active',
                'created_by' => 2,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2021-09-07 18:54:10',
                'updated_at' => '2021-09-07 18:54:10',
                'deleted_at' => NULL,
            ),
            2 => 
            array (
                'id' => 3,
                'name' => 'MORITA',
                'bn_name' => 'মরিটা',
                'country_id' => 108,
                'status' => 'Active',
                'created_by' => 2,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2021-09-07 18:55:48',
                'updated_at' => '2021-09-07 18:55:48',
                'deleted_at' => NULL,
            ),
            3 => 
            array (
                'id' => 4,
                'name' => 'VOLVO',
                'bn_name' => 'ভলভো',
                'country_id' => 204,
                'status' => 'Active',
                'created_by' => 2,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2021-09-07 18:57:14',
                'updated_at' => '2021-09-07 18:57:14',
                'deleted_at' => NULL,
            ),
            4 => 
            array (
                'id' => 5,
                'name' => 'NISSAN',
                'bn_name' => 'নিশান',
                'country_id' => 108,
                'status' => 'Active',
                'created_by' => 2,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2021-09-07 18:59:30',
                'updated_at' => '2021-09-07 18:59:30',
                'deleted_at' => NULL,
            ),
            5 => 
            array (
                'id' => 6,
                'name' => 'TOYOTA',
                'bn_name' => 'টয়োটা',
                'country_id' => 108,
                'status' => 'Active',
                'created_by' => 2,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2021-09-07 19:01:13',
                'updated_at' => '2021-09-07 19:01:13',
                'deleted_at' => NULL,
            ),
            6 => 
            array (
                'id' => 7,
                'name' => 'TATA',
                'bn_name' => 'টাটা',
                'country_id' => 99,
                'status' => 'Active',
                'created_by' => 2,
                'updated_by' => 2,
                'deleted_by' => NULL,
                'created_at' => '2021-09-07 19:08:31',
                'updated_at' => '2021-09-07 19:24:36',
                'deleted_at' => NULL,
            ),
            7 => 
            array (
                'id' => 8,
                'name' => 'FORCE',
                'bn_name' => 'ফোর্স',
                'country_id' => 99,
                'status' => 'Active',
                'created_by' => 2,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2021-09-07 19:24:45',
                'updated_at' => '2021-09-07 19:24:45',
                'deleted_at' => NULL,
            ),
            8 => 
            array (
                'id' => 9,
                'name' => 'JOYLONG',
                'bn_name' => 'জয়লং',
                'country_id' => 45,
                'status' => 'Active',
                'created_by' => 2,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2021-09-07 19:29:08',
                'updated_at' => '2021-09-07 19:29:08',
                'deleted_at' => NULL,
            ),
            9 => 
            array (
                'id' => 10,
                'name' => 'FOTON',
                'bn_name' => 'ফোটন',
                'country_id' => 45,
                'status' => 'Active',
                'created_by' => 2,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2021-09-07 19:30:17',
                'updated_at' => '2021-09-07 19:30:17',
                'deleted_at' => NULL,
            ),
            10 => 
            array (
                'id' => 11,
                'name' => 'TOHATSU',
                'bn_name' => 'টুহাটসু',
                'country_id' => 108,
                'status' => 'Active',
                'created_by' => 2,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2021-09-07 19:50:04',
                'updated_at' => '2021-09-07 19:50:04',
                'deleted_at' => NULL,
            ),
            11 => 
            array (
                'id' => 12,
                'name' => 'SHIBARU',
                'bn_name' => 'শিবারু',
                'country_id' => 108,
                'status' => 'Active',
                'created_by' => 2,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2021-09-07 20:10:05',
                'updated_at' => '2021-09-07 20:10:05',
                'deleted_at' => NULL,
            ),
            12 => 
            array (
                'id' => 14,
                'name' => 'YAMAHA',
                'bn_name' => 'ইয়ামাহা',
                'country_id' => 108,
                'status' => 'Active',
                'created_by' => 2,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2021-09-07 20:32:39',
                'updated_at' => '2021-09-07 20:32:39',
                'deleted_at' => NULL,
            ),
            13 => 
            array (
                'id' => 15,
                'name' => 'SUZUKI',
                'bn_name' => 'সুজুকি',
                'country_id' => 108,
                'status' => 'Active',
                'created_by' => 2,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2021-09-07 20:33:31',
                'updated_at' => '2021-09-07 20:33:31',
                'deleted_at' => NULL,
            ),
            14 => 
            array (
                'id' => 16,
                'name' => 'BEDFORD',
                'bn_name' => 'বেডফোর্ড',
                'country_id' => 223,
                'status' => 'Active',
                'created_by' => 2,
                'updated_by' => 2,
                'deleted_by' => NULL,
                'created_at' => '2021-09-08 16:15:43',
                'updated_at' => '2021-09-08 17:27:25',
                'deleted_at' => NULL,
            ),
            15 => 
            array (
                'id' => 17,
                'name' => 'HONDA',
                'bn_name' => 'হোন্ডা',
                'country_id' => 108,
                'status' => 'Active',
                'created_by' => 2,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2021-09-08 16:46:36',
                'updated_at' => '2021-09-08 16:46:36',
                'deleted_at' => NULL,
            ),
            16 => 
            array (
                'id' => 18,
                'name' => 'PHEONIX',
                'bn_name' => 'ফনিক্স',
                'country_id' => 1,
                'status' => 'Active',
                'created_by' => 2,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2021-09-08 16:52:46',
                'updated_at' => '2021-09-08 16:52:46',
                'deleted_at' => NULL,
            ),
            17 => 
            array (
                'id' => 19,
                'name' => 'HINO',
                'bn_name' => 'হিনো',
                'country_id' => 108,
                'status' => 'Active',
                'created_by' => 2,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2021-09-08 16:56:11',
                'updated_at' => '2021-09-08 16:56:11',
                'deleted_at' => NULL,
            ),
            18 => 
            array (
                'id' => 20,
                'name' => 'FORD',
                'bn_name' => 'ফোর্ড',
                'country_id' => 1,
                'status' => 'Active',
                'created_by' => 2,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2021-09-08 17:24:14',
                'updated_at' => '2021-09-08 17:24:14',
                'deleted_at' => NULL,
            ),
            19 => 
            array (
                'id' => 21,
                'name' => 'MAZDA',
                'bn_name' => 'মাজদা',
                'country_id' => 108,
                'status' => 'Active',
                'created_by' => 2,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2021-09-08 17:30:09',
                'updated_at' => '2021-09-08 17:30:09',
                'deleted_at' => NULL,
            ),
            20 => 
            array (
                'id' => 22,
                'name' => 'MAGIRUS',
                'bn_name' => 'ম্যাগিরাস',
                'country_id' => 81,
                'status' => 'Active',
                'created_by' => 2,
                'updated_by' => 2,
                'deleted_by' => NULL,
                'created_at' => '2021-09-08 19:01:59',
                'updated_at' => '2021-09-14 17:43:00',
                'deleted_at' => NULL,
            ),
            21 => 
            array (
                'id' => 23,
                'name' => 'ELEMAX',
                'bn_name' => 'ইলিমেক্স',
                'country_id' => 108,
                'status' => 'Active',
                'created_by' => 2,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2021-09-08 19:04:41',
                'updated_at' => '2021-09-08 19:04:41',
                'deleted_at' => NULL,
            ),
            22 => 
            array (
                'id' => 24,
                'name' => 'FIRMAN',
                'bn_name' => 'ফিরম্যান',
                'country_id' => 1,
                'status' => 'Active',
                'created_by' => 2,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2021-09-08 19:18:55',
                'updated_at' => '2021-09-08 19:18:55',
                'deleted_at' => NULL,
            ),
            23 => 
            array (
                'id' => 25,
                'name' => 'TBM',
                'bn_name' => 'টিবিএম',
                'country_id' => 108,
                'status' => 'Active',
                'created_by' => 2,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2021-09-08 19:22:17',
                'updated_at' => '2021-09-08 19:22:17',
                'deleted_at' => NULL,
            ),
            24 => 
            array (
                'id' => 26,
                'name' => 'JHON DEERE',
                'bn_name' => 'জন ডিয়ার',
                'country_id' => 1,
                'status' => 'Active',
                'created_by' => 2,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2021-09-08 19:26:45',
                'updated_at' => '2021-09-08 19:26:45',
                'deleted_at' => NULL,
            ),
            25 => 
            array (
                'id' => 27,
                'name' => 'HERO HONDA',
                'bn_name' => 'হিরো হোন্ডা',
                'country_id' => 99,
                'status' => 'Active',
                'created_by' => 2,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2021-09-08 19:30:17',
                'updated_at' => '2021-09-08 19:30:17',
                'deleted_at' => NULL,
            ),
            26 => 
            array (
                'id' => 28,
                'name' => 'ANGUS',
                'bn_name' => 'এ্যাংগাছ',
                'country_id' => 223,
                'status' => 'Active',
                'created_by' => 2,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2021-09-09 16:08:14',
                'updated_at' => '2021-09-09 16:08:14',
                'deleted_at' => NULL,
            ),
            27 => 
            array (
                'id' => 29,
                'name' => 'GODIVA',
                'bn_name' => 'গডিভা',
                'country_id' => 23,
                'status' => 'Active',
                'created_by' => 2,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2021-09-09 16:24:28',
                'updated_at' => '2021-09-09 16:24:28',
                'deleted_at' => NULL,
            ),
            28 => 
            array (
                'id' => 30,
                'name' => 'KUBOTA',
                'bn_name' => 'কুবোতা',
                'country_id' => 108,
                'status' => 'Active',
                'created_by' => 2,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2021-09-09 19:23:28',
                'updated_at' => '2021-09-09 19:23:28',
                'deleted_at' => NULL,
            ),
            29 => 
            array (
                'id' => 31,
                'name' => 'Chevrolet',
                'bn_name' => 'শেভ্রোলেট',
                'country_id' => 1,
                'status' => 'Active',
                'created_by' => 2,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2021-09-12 16:53:14',
                'updated_at' => '2021-09-12 16:53:14',
                'deleted_at' => NULL,
            ),
            30 => 
            array (
                'id' => 32,
                'name' => 'RABBIT',
                'bn_name' => 'রেবিট',
                'country_id' => 223,
                'status' => 'Active',
                'created_by' => 2,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2021-09-12 18:58:41',
                'updated_at' => '2021-09-12 18:58:41',
                'deleted_at' => NULL,
            ),
            31 => 
            array (
                'id' => 33,
                'name' => 'Qingqi',
                'bn_name' => 'কিংকি',
                'country_id' => 45,
                'status' => 'Active',
                'created_by' => 2,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2021-09-12 19:00:12',
                'updated_at' => '2021-09-12 19:00:12',
                'deleted_at' => NULL,
            ),
            32 => 
            array (
                'id' => 34,
                'name' => 'QJIANG',
                'bn_name' => 'কিউজিয়াং',
                'country_id' => 45,
                'status' => 'Active',
                'created_by' => 2,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2021-09-14 19:29:43',
                'updated_at' => '2021-09-14 19:29:43',
                'deleted_at' => NULL,
            ),
        ));
        
        
    }
}