<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class MenusTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('menus')->delete();
        
        \DB::table('menus')->insert(array (
            0 => 
            array (
                'id' => 1,
                'parent_id' => NULL,
                'role_id' => NULL,
                'name' => 'Dashboard',
                'bn_name' => 'ড্যাশবোর্ড',
                'route_name' => 'dashboard',
                'icon' => 'fa fa-home',
                'order_by' => 1,
                'is_hidden' => 'No',
                'status' => 1,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2021-02-25 10:39:06',
                'updated_at' => '2021-07-29 18:30:34',
                'deleted_at' => NULL,
            ),
            1 => 
            array (
                'id' => 2,
                'parent_id' => NULL,
                'role_id' => 1,
                'name' => 'Menu Management',
                'bn_name' => 'Menu Management',
                'route_name' => NULL,
                'icon' => 'fa fa-user',
                'order_by' => 200,
                'is_hidden' => 'No',
                'status' => 1,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2021-02-25 10:41:43',
                'updated_at' => '2021-12-01 08:19:03',
                'deleted_at' => NULL,
            ),
            2 => 
            array (
                'id' => 3,
                'parent_id' => 2,
                'role_id' => NULL,
                'name' => 'Menu',
                'bn_name' => 'মেনু',
                'route_name' => 'menu.index',
                'icon' => NULL,
                'order_by' => 3,
                'is_hidden' => 'No',
                'status' => 1,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2021-02-25 10:42:17',
                'updated_at' => '2021-09-07 15:32:35',
                'deleted_at' => NULL,
            ),
            3 => 
            array (
                'id' => 4,
                'parent_id' => 2,
                'role_id' => NULL,
                'name' => 'Menu Action',
                'bn_name' => 'মেনু একশন',
                'route_name' => 'menu-action.index',
                'icon' => NULL,
                'order_by' => 4,
                'is_hidden' => 'No',
                'status' => 1,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2021-02-25 12:33:53',
                'updated_at' => '2021-09-07 15:45:08',
                'deleted_at' => NULL,
            ),
            4 => 
            array (
                'id' => 5,
                'parent_id' => NULL,
                'role_id' => NULL,
                'name' => 'Arrangement',
                'bn_name' => 'বিন্যাস',
                'route_name' => NULL,
                'icon' => 'fa fa-compress-arrows-alt',
                'order_by' => 20,
                'is_hidden' => 'No',
                'status' => 0,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2021-02-25 15:30:35',
                'updated_at' => '2021-07-29 18:27:32',
                'deleted_at' => NULL,
            ),
            5 => 
            array (
                'id' => 6,
                'parent_id' => 141,
                'role_id' => NULL,
                'name' => 'Division',
                'bn_name' => 'বিভাগ',
                'route_name' => 'division.index',
                'icon' => 'fa fa-disease',
                'order_by' => 2,
                'is_hidden' => 'No',
                'status' => 1,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2021-02-25 15:35:24',
                'updated_at' => '2021-12-02 03:52:35',
                'deleted_at' => NULL,
            ),
            6 => 
            array (
                'id' => 10,
                'parent_id' => 136,
                'role_id' => NULL,
                'name' => 'User Management',
                'bn_name' => 'ইউজার ম্যানেজমেন্ট',
                'route_name' => NULL,
                'icon' => 'fas fa-cogs',
                'order_by' => 3,
                'is_hidden' => 'No',
                'status' => 1,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2021-02-27 16:07:00',
                'updated_at' => '2021-12-02 01:59:59',
                'deleted_at' => NULL,
            ),
            7 => 
            array (
                'id' => 25,
                'parent_id' => NULL,
                'role_id' => NULL,
                'name' => 'Content Setup',
                'bn_name' => 'কনটেন্ট সেটাপ',
                'route_name' => 'content.index',
                'icon' => NULL,
                'order_by' => 50,
                'is_hidden' => 'No',
                'status' => 0,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2021-02-27 16:11:38',
                'updated_at' => '2021-07-29 18:26:53',
                'deleted_at' => NULL,
            ),
            8 => 
            array (
                'id' => 27,
                'parent_id' => NULL,
                'role_id' => NULL,
                'name' => 'ব্যবহারকারীর তালিকা',
                'bn_name' => NULL,
                'route_name' => NULL,
                'icon' => NULL,
                'order_by' => 25,
                'is_hidden' => 'No',
                'status' => 0,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2021-02-27 16:11:52',
                'updated_at' => '2021-06-30 13:16:29',
                'deleted_at' => '2021-06-30 13:16:29',
            ),
            9 => 
            array (
                'id' => 30,
                'parent_id' => 141,
                'role_id' => NULL,
                'name' => 'District',
                'bn_name' => 'জেলা',
                'route_name' => 'district.index',
                'icon' => 'fa fa-compact-disc',
                'order_by' => 3,
                'is_hidden' => 'No',
                'status' => 1,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2021-02-27 16:12:48',
                'updated_at' => '2021-12-02 03:52:45',
                'deleted_at' => NULL,
            ),
            10 => 
            array (
                'id' => 31,
                'parent_id' => 141,
                'role_id' => NULL,
                'name' => 'Upzilla/Thana',
                'bn_name' => 'উপজেলা/থানা',
                'route_name' => 'thana.index',
                'icon' => 'fab fa-discourse',
                'order_by' => 4,
                'is_hidden' => 'No',
                'status' => 1,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2021-02-27 16:12:54',
                'updated_at' => '2021-12-02 03:52:54',
                'deleted_at' => NULL,
            ),
            11 => 
            array (
                'id' => 33,
                'parent_id' => 136,
                'role_id' => NULL,
                'name' => 'Fire Station',
                'bn_name' => 'ফায়ার স্টেশন',
                'route_name' => NULL,
                'icon' => 'fa fa-school',
                'order_by' => 6,
                'is_hidden' => 'No',
                'status' => 1,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2021-02-27 16:13:04',
                'updated_at' => '2021-12-02 02:43:52',
                'deleted_at' => NULL,
            ),
            12 => 
            array (
                'id' => 44,
                'parent_id' => 10,
                'role_id' => NULL,
                'name' => 'Users',
                'bn_name' => 'ব্যবহারকারী',
                'route_name' => 'user.index',
                'icon' => 'fas fa-user-tag',
                'order_by' => 2,
                'is_hidden' => 'No',
                'status' => 1,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2021-02-27 16:18:39',
                'updated_at' => '2021-12-02 02:21:10',
                'deleted_at' => NULL,
            ),
            13 => 
            array (
                'id' => 45,
                'parent_id' => 10,
                'role_id' => NULL,
                'name' => 'Roles Management and Approval',
                'bn_name' => 'রোল ম্যানেজমেন্ট ও অনুমোদন',
                'route_name' => 'role.index',
                'icon' => 'fas fa-user-cog',
                'order_by' => 1,
                'is_hidden' => 'No',
                'status' => 1,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2021-02-27 16:18:47',
                'updated_at' => '2021-12-02 02:20:48',
                'deleted_at' => NULL,
            ),
            14 => 
            array (
                'id' => 49,
                'parent_id' => 33,
                'role_id' => NULL,
                'name' => 'Fire Station List',
                'bn_name' => 'ফায়ার স্টেশনের লিস্ট',
                'route_name' => 'fire_station.index',
                'icon' => 'fas fa-th-list',
                'order_by' => 51,
                'is_hidden' => 'No',
                'status' => 1,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2021-02-27 16:19:36',
                'updated_at' => '2021-07-29 18:19:02',
                'deleted_at' => NULL,
            ),
            15 => 
            array (
                'id' => 63,
                'parent_id' => 33,
                'role_id' => NULL,
                'name' => 'Fire Station Type',
                'bn_name' => 'ফায়ার স্টেশনের শ্রেনী',
                'route_name' => 'fire_station_type.index',
                'icon' => 'fab fa-typo3',
                'order_by' => 50,
                'is_hidden' => 'No',
                'status' => 1,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2021-03-01 17:39:18',
                'updated_at' => '2021-07-29 18:19:10',
                'deleted_at' => NULL,
            ),
            16 => 
            array (
                'id' => 71,
                'parent_id' => 5,
                'role_id' => NULL,
                'name' => 'Custom Element',
                'bn_name' => 'কাস্টম',
                'route_name' => NULL,
                'icon' => NULL,
                'order_by' => 63,
                'is_hidden' => 'Yes',
                'status' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'created_at' => '2021-05-27 14:28:08',
                'updated_at' => '2021-07-04 18:32:05',
                'deleted_at' => '2021-07-04 18:32:05',
            ),
            17 => 
            array (
                'id' => 74,
                'parent_id' => 10,
                'role_id' => NULL,
                'name' => 'Activity Log',
                'bn_name' => 'কার্য বিবরণ',
                'route_name' => NULL,
                'icon' => 'fas fa-user-shield',
                'order_by' => 3,
                'is_hidden' => 'No',
                'status' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'created_at' => '2021-06-17 17:17:53',
                'updated_at' => '2021-12-02 02:16:12',
                'deleted_at' => NULL,
            ),
            18 => 
            array (
                'id' => 75,
                'parent_id' => 141,
                'role_id' => NULL,
                'name' => 'Country',
                'bn_name' => 'দেশ',
                'route_name' => 'country.index',
                'icon' => 'fa fa-flag',
                'order_by' => 1,
                'is_hidden' => 'No',
                'status' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'created_at' => '2021-07-03 18:57:51',
                'updated_at' => '2021-12-02 03:47:20',
                'deleted_at' => NULL,
            ),
            19 => 
            array (
                'id' => 76,
                'parent_id' => 126,
                'role_id' => NULL,
                'name' => 'Brand',
                'bn_name' => 'ব্র্যান্ড',
                'route_name' => 'brand.index',
                'icon' => 'fa fa-bold',
                'order_by' => 3,
                'is_hidden' => 'No',
                'status' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'created_at' => '2021-07-04 17:55:36',
                'updated_at' => '2021-12-02 03:44:14',
                'deleted_at' => NULL,
            ),
            20 => 
            array (
                'id' => 77,
                'parent_id' => 126,
                'role_id' => NULL,
                'name' => 'Model',
                'bn_name' => 'মডেল',
                'route_name' => 'model.index',
                'icon' => 'fa fa-car-crash',
                'order_by' => 4,
                'is_hidden' => 'No',
                'status' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'created_at' => '2021-07-04 18:00:00',
                'updated_at' => '2021-12-02 03:44:24',
                'deleted_at' => NULL,
            ),
            21 => 
            array (
                'id' => 78,
                'parent_id' => 126,
                'role_id' => NULL,
                'name' => 'Vehicle/Pump/Equipment',
                'bn_name' => 'গাড়ি/পাম্প/সরঞ্জাম',
                'route_name' => 'product.index',
                'icon' => 'fa fa-truck-pickup',
                'order_by' => 5,
                'is_hidden' => 'No',
                'status' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'created_at' => '2021-07-04 18:48:57',
                'updated_at' => '2021-12-02 03:43:37',
                'deleted_at' => NULL,
            ),
            22 => 
            array (
                'id' => 79,
                'parent_id' => 93,
                'role_id' => NULL,
                'name' => 'Variation',
                'bn_name' => 'ভেরিয়েশন',
                'route_name' => NULL,
                'icon' => 'fab fa-servicestack',
                'order_by' => 3,
                'is_hidden' => 'No',
                'status' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'created_at' => '2021-07-11 17:28:57',
                'updated_at' => '2021-08-01 15:13:22',
                'deleted_at' => NULL,
            ),
            23 => 
            array (
                'id' => 80,
                'parent_id' => 79,
                'role_id' => NULL,
                'name' => 'Variation Type',
                'bn_name' => 'ভেরিয়েশন টাইপ',
                'route_name' => 'variant_type.index',
                'icon' => 'fas fa-pencil-ruler',
                'order_by' => 1,
                'is_hidden' => 'No',
                'status' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'created_at' => '2021-07-11 17:32:15',
                'updated_at' => '2021-09-07 15:46:37',
                'deleted_at' => NULL,
            ),
            24 => 
            array (
                'id' => 81,
                'parent_id' => 79,
                'role_id' => NULL,
                'name' => 'Variant',
                'bn_name' => 'ভেরিয়েন্ট',
                'route_name' => 'variant.index',
                'icon' => 'fas fa-ruler-combined',
                'order_by' => 2,
                'is_hidden' => 'No',
                'status' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'created_at' => '2021-07-12 18:13:40',
                'updated_at' => '2021-07-15 16:59:48',
                'deleted_at' => NULL,
            ),
            25 => 
            array (
                'id' => 82,
                'parent_id' => 93,
                'role_id' => NULL,
                'name' => 'Unit',
                'bn_name' => 'একক',
                'route_name' => 'unit.index',
                'icon' => 'fa fa-dna',
                'order_by' => 1,
                'is_hidden' => 'No',
                'status' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'created_at' => '2021-07-15 15:47:27',
                'updated_at' => '2021-08-01 15:12:53',
                'deleted_at' => NULL,
            ),
            26 => 
            array (
                'id' => 83,
                'parent_id' => 93,
                'role_id' => NULL,
                'name' => 'Unit Conversion',
                'bn_name' => 'একক পরিবর্তন',
                'route_name' => 'unit_conversion.index',
                'icon' => 'fas fa-recycle',
                'order_by' => 2,
                'is_hidden' => 'No',
                'status' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'created_at' => '2021-07-15 18:45:23',
                'updated_at' => '2021-08-01 15:13:03',
                'deleted_at' => NULL,
            ),
            27 => 
            array (
                'id' => 84,
                'parent_id' => 126,
                'role_id' => NULL,
                'name' => 'Product Part',
                'bn_name' => 'যন্ত্রাংশ',
                'route_name' => 'product_part.index',
                'icon' => 'fas fa-cog',
                'order_by' => 7,
                'is_hidden' => 'No',
                'status' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'created_at' => '2021-07-17 17:12:27',
                'updated_at' => '2021-12-02 03:50:33',
                'deleted_at' => NULL,
            ),
            28 => 
            array (
                'id' => 85,
                'parent_id' => 126,
                'role_id' => NULL,
                'name' => 'Inventory',
                'bn_name' => 'ইনভেন্টরি',
                'route_name' => 'stock_receive.index',
                'icon' => 'fas fa-shopping-cart',
                'order_by' => 1,
                'is_hidden' => 'No',
                'status' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'created_at' => '2021-07-26 10:12:10',
                'updated_at' => '2021-12-02 03:50:06',
                'deleted_at' => NULL,
            ),
            29 => 
            array (
                'id' => 87,
                'parent_id' => NULL,
                'role_id' => NULL,
                'name' => 'Workshop Management',
                'bn_name' => 'ওয়ার্কশপ ব্যবস্থাপনা',
                'route_name' => NULL,
                'icon' => 'fas fa-place-of-worship',
                'order_by' => 4,
                'is_hidden' => 'No',
                'status' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'created_at' => '2021-07-29 18:23:15',
                'updated_at' => '2021-12-01 08:18:44',
                'deleted_at' => NULL,
            ),
            30 => 
            array (
                'id' => 89,
                'parent_id' => 87,
                'role_id' => NULL,
                'name' => 'Workshop Order',
                'bn_name' => 'ওয়ার্কশপ অর্ডার',
                'route_name' => 'workshop_order.index',
                'icon' => 'fas fa-truck-loading',
                'order_by' => 41,
                'is_hidden' => 'No',
                'status' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'created_at' => '2021-07-29 18:25:45',
                'updated_at' => '2021-07-29 18:41:29',
                'deleted_at' => NULL,
            ),
            31 => 
            array (
                'id' => 90,
                'parent_id' => 136,
                'role_id' => NULL,
                'name' => 'Workshop',
                'bn_name' => 'ওয়ার্কশপ',
                'route_name' => NULL,
                'icon' => 'fas fa-warehouse',
                'order_by' => 5,
                'is_hidden' => 'No',
                'status' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'created_at' => '2021-07-31 15:49:00',
                'updated_at' => '2021-12-02 02:36:55',
                'deleted_at' => NULL,
            ),
            32 => 
            array (
                'id' => 91,
                'parent_id' => 127,
                'role_id' => NULL,
                'name' => 'Driver',
                'bn_name' => 'চালক',
                'route_name' => 'driver.index',
                'icon' => 'fas fa-truck',
                'order_by' => 3,
                'is_hidden' => 'No',
                'status' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'created_at' => '2021-08-01 14:40:43',
                'updated_at' => '2021-12-02 03:46:27',
                'deleted_at' => NULL,
            ),
            33 => 
            array (
                'id' => 92,
                'parent_id' => NULL,
                'role_id' => NULL,
                'name' => 'Management',
                'bn_name' => 'ব্যবস্থাপনা',
                'route_name' => NULL,
                'icon' => 'fas fa-',
                'order_by' => 40,
                'is_hidden' => 'No',
                'status' => 0,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'created_at' => '2021-08-01 14:51:52',
                'updated_at' => '2021-08-01 15:17:35',
                'deleted_at' => NULL,
            ),
            34 => 
            array (
                'id' => 93,
                'parent_id' => 136,
                'role_id' => NULL,
                'name' => 'Attributes Management',
                'bn_name' => 'বৈশিষ্ট্য ব্যবস্থাপনা',
                'route_name' => NULL,
                'icon' => 'fab fa-artstation',
                'order_by' => 2,
                'is_hidden' => 'No',
                'status' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'created_at' => '2021-08-01 15:09:03',
                'updated_at' => '2021-12-02 01:56:19',
                'deleted_at' => NULL,
            ),
            35 => 
            array (
                'id' => 94,
                'parent_id' => 127,
                'role_id' => NULL,
                'name' => 'Employee / Officer',
                'bn_name' => 'কর্মচারী/ কর্মকর্তা',
                'route_name' => 'employee.index',
                'icon' => 'far fa-user',
                'order_by' => 1,
                'is_hidden' => 'No',
                'status' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'created_at' => '2021-08-02 14:36:31',
                'updated_at' => '2021-12-02 02:51:18',
                'deleted_at' => NULL,
            ),
            36 => 
            array (
                'id' => 95,
                'parent_id' => 127,
                'role_id' => NULL,
                'name' => 'Designation',
                'bn_name' => 'উপাধি',
                'route_name' => 'designation.index',
                'icon' => 'fas fa-user-check',
                'order_by' => 4,
                'is_hidden' => 'No',
                'status' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'created_at' => '2021-08-02 16:43:39',
                'updated_at' => '2021-12-02 03:51:34',
                'deleted_at' => NULL,
            ),
            37 => 
            array (
                'id' => 96,
                'parent_id' => 127,
                'role_id' => NULL,
                'name' => 'Supplier',
                'bn_name' => 'সরবরাহকারী',
                'route_name' => 'supplier.index',
                'icon' => 'fas fa-male',
                'order_by' => 5,
                'is_hidden' => 'No',
                'status' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'created_at' => '2021-08-12 15:05:50',
                'updated_at' => '2021-12-06 21:43:32',
                'deleted_at' => NULL,
            ),
            38 => 
            array (
                'id' => 97,
                'parent_id' => 127,
                'role_id' => NULL,
                'name' => 'Driver Assign',
                'bn_name' => 'চালক নিয়োগ',
                'route_name' => 'driver_assign.index',
                'icon' => 'fas fa-taxi',
                'order_by' => 2,
                'is_hidden' => 'No',
                'status' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'created_at' => '2021-08-21 10:05:38',
                'updated_at' => '2021-12-06 20:31:28',
                'deleted_at' => NULL,
            ),
            39 => 
            array (
                'id' => 98,
                'parent_id' => 126,
                'role_id' => NULL,
                'name' => 'Type',
                'bn_name' => 'প্রকার',
                'route_name' => 'type.index',
                'icon' => 'fas fa-exchange-alt',
                'order_by' => 1,
                'is_hidden' => 'No',
                'status' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'created_at' => '2021-09-07 15:48:36',
                'updated_at' => '2021-12-06 21:54:26',
                'deleted_at' => NULL,
            ),
            40 => 
            array (
                'id' => 99,
                'parent_id' => 126,
                'role_id' => NULL,
                'name' => 'Category',
                'bn_name' => 'ধরন',
                'route_name' => 'category.index',
                'icon' => 'fas fa-sort',
                'order_by' => 2,
                'is_hidden' => 'No',
                'status' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'created_at' => '2021-09-07 16:01:52',
                'updated_at' => '2021-12-06 21:50:21',
                'deleted_at' => NULL,
            ),
            41 => 
            array (
                'id' => 100,
                'parent_id' => NULL,
                'role_id' => NULL,
                'name' => 'Log / History Book',
                'bn_name' => 'লগ/ইতিহাস বই',
                'route_name' => NULL,
                'icon' => 'fas fa-file-alt',
                'order_by' => 5,
                'is_hidden' => 'No',
                'status' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'created_at' => '2021-11-15 12:57:45',
                'updated_at' => '2021-12-01 08:22:07',
                'deleted_at' => NULL,
            ),
            42 => 
            array (
                'id' => 101,
                'parent_id' => 131,
                'role_id' => NULL,
                'name' => 'Lubricant Record',
                'bn_name' => 'লুব্রিকেন্ট রেকর্ড',
                'route_name' => 'lubricant_record.index',
                'icon' => 'fas fa-oil-can',
                'order_by' => 3,
                'is_hidden' => 'No',
                'status' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'created_at' => '2021-11-15 13:45:58',
                'updated_at' => '2021-12-02 01:25:36',
                'deleted_at' => NULL,
            ),
            43 => 
            array (
                'id' => 102,
                'parent_id' => 131,
                'role_id' => NULL,
                'name' => 'Filter Change Record',
                'bn_name' => 'ফিল্টার বদলি রেকর্ড',
                'route_name' => 'filter_change_record.index',
                'icon' => 'fas fa-filter',
                'order_by' => 4,
                'is_hidden' => 'No',
                'status' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'created_at' => '2021-11-15 13:55:31',
                'updated_at' => '2021-12-02 01:25:58',
                'deleted_at' => NULL,
            ),
            44 => 
            array (
                'id' => 104,
                'parent_id' => 100,
                'role_id' => NULL,
                'name' => 'Repair Summary',
                'bn_name' => 'মেরামতের সংক্ষিপ্তসার',
                'route_name' => 'repair_summary.index',
                'icon' => 'fas fa-tools',
                'order_by' => 3,
                'is_hidden' => 'No',
                'status' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'created_at' => '2021-11-20 16:22:52',
                'updated_at' => '2021-11-20 16:22:52',
                'deleted_at' => NULL,
            ),
            45 => 
            array (
                'id' => 105,
                'parent_id' => 131,
                'role_id' => NULL,
                'name' => 'Mileage Record',
                'bn_name' => 'মাইলেজ রেকর্ড',
                'route_name' => 'kmpl_lph_record.index',
                'icon' => 'fas fa-clipboard',
                'order_by' => 2,
                'is_hidden' => 'No',
                'status' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'created_at' => '2021-11-22 10:46:57',
                'updated_at' => '2021-12-02 01:25:11',
                'deleted_at' => NULL,
            ),
            46 => 
            array (
                'id' => 106,
                'parent_id' => 129,
                'role_id' => NULL,
                'name' => 'Vehicle Transfer',
                'bn_name' => 'গাড়ি/পাম্প বদলী',
                'route_name' => 'vehicle_transfer.index',
                'icon' => 'fas fa-truck-pickup',
                'order_by' => 1,
                'is_hidden' => 'No',
                'status' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'created_at' => '2021-11-23 15:21:37',
                'updated_at' => '2021-12-02 01:08:56',
                'deleted_at' => NULL,
            ),
            47 => 
            array (
                'id' => 107,
                'parent_id' => 129,
                'role_id' => NULL,
                'name' => 'Driver Record',
                'bn_name' => 'চালকের রেকর্ড',
                'route_name' => 'driver_record.index',
                'icon' => 'fas fa-car',
                'order_by' => 2,
                'is_hidden' => 'No',
                'status' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'created_at' => '2021-11-23 15:39:47',
                'updated_at' => '2021-12-02 01:09:39',
                'deleted_at' => NULL,
            ),
            48 => 
            array (
                'id' => 125,
                'parent_id' => 133,
                'role_id' => NULL,
                'name' => 'Tyre Record',
                'bn_name' => 'টায়ার রেকর্ড',
                'route_name' => 'tyre_record.index',
                'icon' => 'fal fa-dharmachakra',
                'order_by' => 1,
                'is_hidden' => 'No',
                'status' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'created_at' => '2021-11-28 10:04:56',
                'updated_at' => '2021-12-06 20:40:37',
                'deleted_at' => NULL,
            ),
            49 => 
            array (
                'id' => 126,
                'parent_id' => NULL,
                'role_id' => NULL,
                'name' => 'Inventory Arrangement',
                'bn_name' => 'ইনভেন্টরি বিন্যাস',
                'route_name' => NULL,
                'icon' => 'fas fa-biohazard',
                'order_by' => 2,
                'is_hidden' => 'No',
                'status' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'created_at' => '2021-12-01 08:09:41',
                'updated_at' => '2021-12-06 20:27:00',
                'deleted_at' => NULL,
            ),
            50 => 
            array (
                'id' => 127,
                'parent_id' => NULL,
                'role_id' => NULL,
                'name' => 'Manpower',
                'bn_name' => 'জনবল',
                'route_name' => NULL,
                'icon' => 'fas fa-users',
                'order_by' => 3,
                'is_hidden' => 'No',
                'status' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'created_at' => '2021-12-01 08:14:43',
                'updated_at' => '2021-12-06 20:28:48',
                'deleted_at' => NULL,
            ),
            51 => 
            array (
                'id' => 129,
                'parent_id' => 100,
                'role_id' => NULL,
                'name' => 'Log',
                'bn_name' => 'বিবরণ',
                'route_name' => NULL,
                'icon' => 'fas fa-asterisk',
                'order_by' => 1,
                'is_hidden' => 'No',
                'status' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'created_at' => '2021-12-02 01:07:30',
                'updated_at' => '2021-12-06 20:34:01',
                'deleted_at' => NULL,
            ),
            52 => 
            array (
                'id' => 131,
                'parent_id' => 100,
                'role_id' => NULL,
                'name' => 'Lubricant and Filter',
                'bn_name' => 'লুব্রিকেশন ও ফিল্টার',
                'route_name' => NULL,
                'icon' => 'fas fa-filter',
                'order_by' => 2,
                'is_hidden' => 'No',
                'status' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'created_at' => '2021-12-02 01:12:45',
                'updated_at' => '2021-12-06 20:35:45',
                'deleted_at' => NULL,
            ),
            53 => 
            array (
                'id' => 133,
                'parent_id' => 100,
                'role_id' => NULL,
                'name' => 'Tyre and Battery',
                'bn_name' => 'টায়ার ও ব্যাটারি',
                'route_name' => NULL,
                'icon' => 'fas fa-car-battery',
                'order_by' => 4,
                'is_hidden' => 'No',
                'status' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'created_at' => '2021-12-02 01:33:00',
                'updated_at' => '2021-12-06 20:42:50',
                'deleted_at' => NULL,
            ),
            54 => 
            array (
                'id' => 135,
                'parent_id' => 100,
                'role_id' => NULL,
                'name' => 'Permanent Order Information',
                'bn_name' => 'স্থায়ী আদেশাবলীর তথ্য',
                'route_name' => NULL,
                'icon' => NULL,
                'order_by' => 5,
                'is_hidden' => 'No',
                'status' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'created_at' => '2021-12-02 01:45:34',
                'updated_at' => '2021-12-04 02:54:50',
                'deleted_at' => '2021-12-04 02:54:50',
            ),
            55 => 
            array (
                'id' => 136,
                'parent_id' => NULL,
                'role_id' => NULL,
                'name' => 'Setting',
                'bn_name' => 'সেটিং',
                'route_name' => NULL,
                'icon' => 'fas fa-cog',
                'order_by' => 6,
                'is_hidden' => 'No',
                'status' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'created_at' => '2021-12-02 01:48:21',
                'updated_at' => '2021-12-06 20:44:59',
                'deleted_at' => NULL,
            ),
            56 => 
            array (
                'id' => 137,
                'parent_id' => 136,
                'role_id' => NULL,
                'name' => 'General Configuration',
                'bn_name' => 'সাধারণ কনফিগারেশন',
                'route_name' => NULL,
                'icon' => 'fas fa-archway',
                'order_by' => 1,
                'is_hidden' => 'No',
                'status' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'created_at' => '2021-12-02 01:54:28',
                'updated_at' => '2021-12-06 20:47:34',
                'deleted_at' => NULL,
            ),
            57 => 
            array (
                'id' => 139,
                'parent_id' => 74,
                'role_id' => NULL,
                'name' => 'Login Activity',
                'bn_name' => 'লগিন এক্টিভিটি',
                'route_name' => NULL,
                'icon' => NULL,
                'order_by' => 1,
                'is_hidden' => 'No',
                'status' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'created_at' => '2021-12-02 02:03:34',
                'updated_at' => '2021-12-02 02:03:34',
                'deleted_at' => NULL,
            ),
            58 => 
            array (
                'id' => 140,
                'parent_id' => 74,
                'role_id' => NULL,
                'name' => 'User Activity Log',
                'bn_name' => 'ব্যবহারকারীর কার্য বিবরণ',
                'route_name' => 'activity_log.index',
                'icon' => NULL,
                'order_by' => 2,
                'is_hidden' => 'No',
                'status' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'created_at' => '2021-12-02 02:16:48',
                'updated_at' => '2021-12-02 02:16:48',
                'deleted_at' => NULL,
            ),
            59 => 
            array (
                'id' => 141,
                'parent_id' => 136,
                'role_id' => NULL,
                'name' => 'Area',
                'bn_name' => 'এলাকা',
                'route_name' => NULL,
                'icon' => 'fas fa-chart-area',
                'order_by' => 4,
                'is_hidden' => 'No',
                'status' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'created_at' => '2021-12-02 02:33:37',
                'updated_at' => '2021-12-06 20:49:04',
                'deleted_at' => NULL,
            ),
            60 => 
            array (
                'id' => 142,
                'parent_id' => 90,
                'role_id' => NULL,
                'name' => 'Workshop List',
                'bn_name' => 'ওয়ার্কশপ লিস্ট',
                'route_name' => 'workshop.index',
                'icon' => NULL,
                'order_by' => 2,
                'is_hidden' => 'No',
                'status' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'created_at' => '2021-12-02 02:38:21',
                'updated_at' => '2021-12-02 02:38:21',
                'deleted_at' => NULL,
            ),
            61 => 
            array (
                'id' => 143,
                'parent_id' => 90,
                'role_id' => NULL,
                'name' => 'Workshop Class',
                'bn_name' => 'ওয়ার্কশপ শ্রেনী',
                'route_name' => NULL,
                'icon' => NULL,
                'order_by' => 1,
                'is_hidden' => 'No',
                'status' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'created_at' => '2021-12-02 02:40:21',
                'updated_at' => '2021-12-02 02:40:21',
                'deleted_at' => NULL,
            ),
            62 => 
            array (
                'id' => 144,
                'parent_id' => 136,
                'role_id' => NULL,
                'name' => 'API Management',
                'bn_name' => 'এ পি আই ব্যবস্থাপনা',
                'route_name' => NULL,
                'icon' => 'fas fa-tasks',
                'order_by' => 7,
                'is_hidden' => 'No',
                'status' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'created_at' => '2021-12-02 02:48:16',
                'updated_at' => '2021-12-06 20:53:13',
                'deleted_at' => NULL,
            ),
            63 => 
            array (
                'id' => 145,
                'parent_id' => 129,
                'role_id' => NULL,
                'name' => 'Inspection / Testing',
                'bn_name' => 'পরিদর্শন/ পরীক্ষণ',
                'route_name' => 'inspection_testing.index',
                'icon' => 'fad fa-bars',
                'order_by' => 3,
                'is_hidden' => 'No',
                'status' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'created_at' => '2021-12-01 01:18:08',
                'updated_at' => '2021-12-01 01:26:44',
                'deleted_at' => NULL,
            ),
            64 => 
            array (
                'id' => 147,
                'parent_id' => 100,
                'role_id' => NULL,
                'name' => 'Permanent Order Information',
                'bn_name' => 'স্থায়ী আদেশাবলীর তথ্য',
                'route_name' => 'vehicle_maintenance_order.index',
                'icon' => 'fab fa-first-order',
                'order_by' => 5,
                'is_hidden' => 'No',
                'status' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'created_at' => '2021-12-04 02:58:28',
                'updated_at' => '2021-12-04 02:58:28',
                'deleted_at' => NULL,
            ),
            65 => 
            array (
                'id' => 148,
                'parent_id' => 133,
                'role_id' => NULL,
                'name' => 'Battery Details',
                'bn_name' => 'ব্যাটারির বিবরণ',
                'route_name' => 'battery_record.index',
                'icon' => 'fas fa-car-battery',
                'order_by' => 2,
                'is_hidden' => 'No',
                'status' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'created_at' => '2021-12-05 02:02:44',
                'updated_at' => '2021-12-05 02:02:44',
                'deleted_at' => NULL,
            ),
            66 => 
            array (
                'id' => 150,
                'parent_id' => 131,
                'role_id' => NULL,
                'name' => 'Monthly Transit',
                'bn_name' => 'চলাচলের হিসাব',
                'route_name' => 'monthly_transit.index',
                'icon' => 'fas fa-calculator',
                'order_by' => 1,
                'is_hidden' => 'No',
                'status' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'created_at' => '2021-12-06 23:36:05',
                'updated_at' => '2021-12-06 23:36:05',
                'deleted_at' => NULL,
            ),
            67 => 
            array (
                'id' => 151,
                'parent_id' => NULL,
                'role_id' => NULL,
                'name' => 'Requisition',
                'bn_name' => 'চাহিদাপত্র',
                'route_name' => NULL,
                'icon' => 'bx bxs-bookmarks',
                'order_by' => 5,
                'is_hidden' => 'No',
                'status' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'created_at' => '2022-01-02 21:40:27',
                'updated_at' => '2022-01-02 21:40:27',
                'deleted_at' => NULL,
            ),
            68 => 
            array (
                'id' => 152,
                'parent_id' => 151,
                'role_id' => NULL,
                'name' => 'Requisition Add',
                'bn_name' => 'চাহিদাপত্র সংযোজন',
                'route_name' => 'requisition.create',
                'icon' => 'far fa-arrow-alt-circle-right',
                'order_by' => 1,
                'is_hidden' => 'No',
                'status' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'created_at' => '2022-01-02 21:52:03',
                'updated_at' => '2022-01-02 22:00:35',
                'deleted_at' => NULL,
            ),
            69 => 
            array (
                'id' => 153,
                'parent_id' => 151,
                'role_id' => NULL,
                'name' => 'Requisition List',
                'bn_name' => 'চাহিদাপত্রের তালিকা',
                'route_name' => 'requisition.index',
                'icon' => 'fas fa-indent',
                'order_by' => 2,
                'is_hidden' => 'No',
                'status' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'created_at' => '2022-01-02 21:58:32',
                'updated_at' => '2022-01-02 21:58:32',
                'deleted_at' => NULL,
            ),
            70 => 
            array (
                'id' => 154,
                'parent_id' => 87,
                'role_id' => NULL,
                'name' => 'Repair Job Card',
                'bn_name' => 'মেরামতি জব কার্ড',
                'route_name' => 'repair_job_card.index',
                'icon' => 'fas fa-wrench',
                'order_by' => 44,
                'is_hidden' => 'No',
                'status' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'created_at' => '2022-01-21 06:16:45',
                'updated_at' => '2022-01-21 06:16:45',
                'deleted_at' => NULL,
            ),
            71 => 
            array (
                'id' => 155,
                'parent_id' => 87,
                'role_id' => NULL,
                'name' => 'Inspection',
                'bn_name' => 'পরিদর্শন',
                'route_name' => 'inspection_report.index',
                'icon' => 'fas fa-hospital-user',
                'order_by' => 43,
                'is_hidden' => 'No',
                'status' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'created_at' => '2022-01-22 16:29:09',
                'updated_at' => '2022-01-22 16:29:09',
                'deleted_at' => NULL,
            ),
        ));
        
        
    }
}