<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class ModelsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('models')->delete();
        
        \DB::table('models')->insert(array (
            0 => 
            array (
                'id' => 1,
                'brand_id' => 1,
                'name' => 'FK-415h',
                'bn_name' => 'FK-415h',
                'status' => 'Active',
                'created_by' => 2,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2021-09-08 20:36:08',
                'updated_at' => '2021-09-08 20:36:08',
                'deleted_at' => NULL,
            ),
            1 => 
            array (
                'id' => 2,
                'brand_id' => 1,
                'name' => '8DC8',
                'bn_name' => '8DC8',
                'status' => 'Active',
                'created_by' => 2,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2021-09-08 20:36:43',
                'updated_at' => '2021-09-08 20:36:43',
                'deleted_at' => NULL,
            ),
            2 => 
            array (
                'id' => 3,
                'brand_id' => 2,
                'name' => 'JAANHR55EA',
                'bn_name' => 'JAANHR55EA',
                'status' => 'Active',
                'created_by' => 2,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2021-09-08 20:37:34',
                'updated_at' => '2021-09-08 20:37:34',
                'deleted_at' => NULL,
            ),
            3 => 
            array (
                'id' => 4,
                'brand_id' => 1,
                'name' => 'JALFTR33K',
                'bn_name' => 'JALFTR33K',
                'status' => 'Active',
                'created_by' => 2,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2021-09-08 20:39:21',
                'updated_at' => '2021-09-08 20:39:21',
                'deleted_at' => NULL,
            ),
            4 => 
            array (
                'id' => 5,
                'brand_id' => 1,
                'name' => 'FM617H',
                'bn_name' => 'FM617H',
                'status' => 'Active',
                'created_by' => 2,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2021-09-08 20:40:04',
                'updated_at' => '2021-09-08 20:40:04',
                'deleted_at' => NULL,
            ),
            5 => 
            array (
                'id' => 6,
                'brand_id' => 1,
                'name' => 'FE-211C',
                'bn_name' => 'FE-211C',
                'status' => 'Active',
                'created_by' => 2,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2021-09-09 15:31:52',
                'updated_at' => '2021-09-09 15:31:52',
                'deleted_at' => NULL,
            ),
            6 => 
            array (
                'id' => 7,
                'brand_id' => 1,
                'name' => 'FE71PB',
                'bn_name' => 'FE71PB',
                'status' => 'Active',
                'created_by' => 2,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2021-09-09 15:32:36',
                'updated_at' => '2021-09-09 15:32:36',
                'deleted_at' => NULL,
            ),
            7 => 
            array (
                'id' => 8,
                'brand_id' => 2,
                'name' => 'JALFTS33F',
                'bn_name' => 'JALFTS33F',
                'status' => 'Active',
                'created_by' => 2,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2021-09-09 15:33:32',
                'updated_at' => '2021-09-09 15:33:32',
                'deleted_at' => NULL,
            ),
            8 => 
            array (
                'id' => 9,
                'brand_id' => 2,
                'name' => 'JALFSR3',
                'bn_name' => 'JALFSR3',
                'status' => 'Active',
                'created_by' => 2,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2021-09-09 15:34:39',
                'updated_at' => '2021-09-09 15:34:39',
                'deleted_at' => NULL,
            ),
            9 => 
            array (
                'id' => 10,
                'brand_id' => 2,
                'name' => 'JATTG4E25XO',
                'bn_name' => 'JATTG4E25XO',
                'status' => 'Active',
                'created_by' => 2,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2021-09-09 15:38:09',
                'updated_at' => '2021-09-09 15:38:09',
                'deleted_at' => NULL,
            ),
            10 => 
            array (
                'id' => 11,
                'brand_id' => 5,
                'name' => 'INITA4E25Z',
                'bn_name' => 'INITA4E25Z',
                'status' => 'Active',
                'created_by' => 2,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2021-09-09 15:39:02',
                'updated_at' => '2021-09-09 15:39:02',
                'deleted_at' => NULL,
            ),
            11 => 
            array (
                'id' => 12,
                'brand_id' => 5,
                'name' => 'JNIUBHW',
                'bn_name' => 'JNIUBHW',
                'status' => 'Active',
                'created_by' => 2,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2021-09-09 15:39:33',
                'updated_at' => '2021-09-09 15:39:33',
                'deleted_at' => NULL,
            ),
            12 => 
            array (
                'id' => 13,
                'brand_id' => 5,
                'name' => 'JNICEAN16JO',
                'bn_name' => 'JNICEAN16JO',
                'status' => 'Active',
                'created_by' => 2,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2021-09-09 15:41:24',
                'updated_at' => '2021-09-09 15:41:24',
                'deleted_at' => NULL,
            ),
            13 => 
            array (
                'id' => 14,
                'brand_id' => 1,
                'name' => 'MMBJNKB40DD',
                'bn_name' => 'MMBJNKB40DD',
                'status' => 'Active',
                'created_by' => 2,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2021-09-09 15:43:54',
                'updated_at' => '2021-09-09 15:43:54',
                'deleted_at' => NULL,
            ),
            14 => 
            array (
                'id' => 15,
                'brand_id' => 1,
                'name' => 'LWBP',
                'bn_name' => 'LWBP',
                'status' => 'Active',
                'created_by' => 2,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2021-09-09 15:45:52',
                'updated_at' => '2021-09-09 15:45:52',
                'deleted_at' => NULL,
            ),
            15 => 
            array (
                'id' => 16,
                'brand_id' => 1,
                'name' => 'PLSUVKH4W',
                'bn_name' => 'PLSUVKH4W',
                'status' => 'Active',
                'created_by' => 2,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2021-09-09 16:03:23',
                'updated_at' => '2021-09-09 16:03:23',
                'deleted_at' => NULL,
            ),
            16 => 
            array (
                'id' => 17,
                'brand_id' => 10,
                'name' => 'BJ2037Y3MDV',
                'bn_name' => 'BJ2037Y3MDV',
                'status' => 'Active',
                'created_by' => 2,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2021-09-09 16:04:08',
                'updated_at' => '2021-09-09 16:04:08',
                'deleted_at' => NULL,
            ),
            17 => 
            array (
                'id' => 18,
                'brand_id' => 2,
                'name' => 'NPR-66A',
                'bn_name' => 'NPR-66A',
                'status' => 'Active',
                'created_by' => 2,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2021-09-09 16:04:31',
                'updated_at' => '2021-09-09 16:04:31',
                'deleted_at' => NULL,
            ),
            18 => 
            array (
                'id' => 19,
                'brand_id' => 1,
                'name' => 'K34TUNSR',
                'bn_name' => 'K34TUNSR',
                'status' => 'Active',
                'created_by' => 2,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2021-09-09 16:05:05',
                'updated_at' => '2021-09-09 16:05:05',
                'deleted_at' => NULL,
            ),
            19 => 
            array (
                'id' => 20,
                'brand_id' => 28,
                'name' => 'LW-1300',
                'bn_name' => 'LW-1300',
                'status' => 'Active',
                'created_by' => 2,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2021-09-09 16:09:53',
                'updated_at' => '2021-09-09 16:09:53',
                'deleted_at' => NULL,
            ),
            20 => 
            array (
                'id' => 21,
                'brand_id' => 28,
                'name' => 'LW-2300',
                'bn_name' => 'LW-2300',
                'status' => 'Active',
                'created_by' => 2,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2021-09-09 16:11:04',
                'updated_at' => '2021-09-09 16:11:04',
                'deleted_at' => NULL,
            ),
            21 => 
            array (
                'id' => 22,
                'brand_id' => 2,
                'name' => 'FTR-33H',
                'bn_name' => 'FTR-33H',
                'status' => 'Active',
                'created_by' => 2,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2021-09-09 16:21:02',
                'updated_at' => '2021-09-09 16:21:02',
                'deleted_at' => NULL,
            ),
            22 => 
            array (
                'id' => 23,
                'brand_id' => 2,
                'name' => 'NHR',
                'bn_name' => 'NHR',
                'status' => 'Active',
                'created_by' => 2,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2021-09-09 16:21:26',
                'updated_at' => '2021-09-09 16:21:26',
                'deleted_at' => NULL,
            ),
            23 => 
            array (
                'id' => 24,
                'brand_id' => 1,
                'name' => 'L-200',
                'bn_name' => 'L-200',
                'status' => 'Active',
                'created_by' => 2,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2021-09-09 16:22:26',
                'updated_at' => '2021-09-09 16:22:26',
                'deleted_at' => NULL,
            ),
            24 => 
            array (
                'id' => 25,
                'brand_id' => 11,
                'name' => 'VC-82ASE',
                'bn_name' => 'VC-82ASE',
                'status' => 'Active',
                'created_by' => 2,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2021-09-09 16:25:34',
                'updated_at' => '2021-09-09 16:25:34',
                'deleted_at' => NULL,
            ),
            25 => 
            array (
                'id' => 26,
                'brand_id' => 29,
                'name' => 'GP-2300',
                'bn_name' => 'GP-2300',
                'status' => 'Active',
                'created_by' => 2,
                'updated_by' => 2,
                'deleted_by' => NULL,
                'created_at' => '2021-09-09 16:26:10',
                'updated_at' => '2021-09-09 19:48:33',
                'deleted_at' => NULL,
            ),
            26 => 
            array (
                'id' => 27,
                'brand_id' => 29,
                'name' => 'GP-10/10',
                'bn_name' => 'GP-10/10',
                'status' => 'Active',
                'created_by' => 2,
                'updated_by' => 2,
                'deleted_by' => NULL,
                'created_at' => '2021-09-09 16:26:23',
                'updated_at' => '2021-09-09 16:27:31',
                'deleted_at' => NULL,
            ),
            27 => 
            array (
                'id' => 28,
                'brand_id' => 2,
                'name' => 'NPR',
                'bn_name' => 'NPR',
                'status' => 'Active',
                'created_by' => 2,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2021-09-09 16:31:12',
                'updated_at' => '2021-09-09 16:31:12',
                'deleted_at' => NULL,
            ),
            28 => 
            array (
                'id' => 29,
                'brand_id' => 5,
                'name' => 'FH 60',
                'bn_name' => 'FH 60',
                'status' => 'Active',
                'created_by' => 2,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2021-09-09 16:31:40',
                'updated_at' => '2021-09-09 16:31:40',
                'deleted_at' => NULL,
            ),
            29 => 
            array (
                'id' => 30,
                'brand_id' => 11,
                'name' => 'V-52',
                'bn_name' => 'V-52',
                'status' => 'Active',
                'created_by' => 2,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2021-09-09 16:32:53',
                'updated_at' => '2021-09-09 16:32:53',
                'deleted_at' => NULL,
            ),
            30 => 
            array (
                'id' => 31,
                'brand_id' => 2,
                'name' => 'CXZ-800/6X 25FVZ',
                'bn_name' => 'CXZ-800/6X 25FVZ',
                'status' => 'Active',
                'created_by' => 2,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2021-09-09 16:37:44',
                'updated_at' => '2021-09-09 16:37:44',
                'deleted_at' => NULL,
            ),
            31 => 
            array (
                'id' => 32,
                'brand_id' => 1,
                'name' => 'FV-515',
                'bn_name' => 'FV-515',
                'status' => 'Active',
                'created_by' => 2,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2021-09-09 16:38:18',
                'updated_at' => '2021-09-09 16:38:18',
                'deleted_at' => NULL,
            ),
            32 => 
            array (
                'id' => 33,
                'brand_id' => 2,
                'name' => 'NHR-55E',
                'bn_name' => 'NHR-55E',
                'status' => 'Active',
                'created_by' => 2,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2021-09-09 16:39:01',
                'updated_at' => '2021-09-09 16:39:01',
                'deleted_at' => NULL,
            ),
            33 => 
            array (
                'id' => 34,
                'brand_id' => 29,
            'name' => 'LW-2275(G)',
            'bn_name' => 'LW-2275(G)',
                'status' => 'Active',
                'created_by' => 2,
                'updated_by' => 2,
                'deleted_by' => 2,
                'created_at' => '2021-09-09 16:40:18',
                'updated_at' => '2021-09-12 20:28:12',
                'deleted_at' => '2021-09-12 20:28:12',
            ),
            34 => 
            array (
                'id' => 35,
                'brand_id' => 11,
                'name' => 'V-75',
                'bn_name' => 'V-75',
                'status' => 'Active',
                'created_by' => 2,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2021-09-09 16:40:39',
                'updated_at' => '2021-09-09 16:40:39',
                'deleted_at' => NULL,
            ),
            35 => 
            array (
                'id' => 36,
                'brand_id' => 14,
                'name' => '5-KA',
                'bn_name' => '5-KA',
                'status' => 'Active',
                'created_by' => 2,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2021-09-09 16:47:11',
                'updated_at' => '2021-09-09 16:47:11',
                'deleted_at' => NULL,
            ),
            36 => 
            array (
                'id' => 37,
                'brand_id' => 6,
            'name' => 'L-300(T)',
            'bn_name' => 'L-300(T)',
                'status' => 'Active',
                'created_by' => 2,
                'updated_by' => 2,
                'deleted_by' => NULL,
                'created_at' => '2021-09-09 16:48:05',
                'updated_at' => '2021-09-09 20:59:28',
                'deleted_at' => NULL,
            ),
            37 => 
            array (
                'id' => 38,
                'brand_id' => 18,
                'name' => '1900',
                'bn_name' => '1900',
                'status' => 'Active',
                'created_by' => 2,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2021-09-09 16:49:39',
                'updated_at' => '2021-09-09 16:49:39',
                'deleted_at' => NULL,
            ),
            38 => 
            array (
                'id' => 39,
                'brand_id' => 2,
                'name' => 'JALFTR33HH',
                'bn_name' => 'JALFTR33HH',
                'status' => 'Active',
                'created_by' => 2,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2021-09-09 16:50:53',
                'updated_at' => '2021-09-09 16:50:53',
                'deleted_at' => NULL,
            ),
            39 => 
            array (
                'id' => 40,
                'brand_id' => 2,
                'name' => 'FTR-33K',
                'bn_name' => 'FTR-33K',
                'status' => 'Active',
                'created_by' => 2,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2021-09-09 16:51:50',
                'updated_at' => '2021-09-09 16:51:50',
                'deleted_at' => NULL,
            ),
            40 => 
            array (
                'id' => 41,
                'brand_id' => 11,
                'name' => 'VC52AS',
                'bn_name' => 'VC52AS',
                'status' => 'Active',
                'created_by' => 2,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2021-09-09 16:52:18',
                'updated_at' => '2021-09-09 16:52:18',
                'deleted_at' => NULL,
            ),
            41 => 
            array (
                'id' => 42,
                'brand_id' => 16,
                'name' => 'J-6',
                'bn_name' => 'J-6',
                'status' => 'Active',
                'created_by' => 2,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2021-09-09 16:55:43',
                'updated_at' => '2021-09-09 16:55:43',
                'deleted_at' => NULL,
            ),
            42 => 
            array (
                'id' => 43,
                'brand_id' => 29,
                'name' => 'GP-12/10',
                'bn_name' => 'GP-12/10',
                'status' => 'Active',
                'created_by' => 2,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2021-09-09 17:41:24',
                'updated_at' => '2021-09-09 17:41:24',
                'deleted_at' => NULL,
            ),
            43 => 
            array (
                'id' => 44,
                'brand_id' => 2,
                'name' => 'FTR5MF',
                'bn_name' => 'FTR5MF',
                'status' => 'Active',
                'created_by' => 2,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2021-09-09 17:42:20',
                'updated_at' => '2021-09-09 17:42:20',
                'deleted_at' => NULL,
            ),
            44 => 
            array (
                'id' => 45,
                'brand_id' => 15,
                'name' => 'KLPE-37',
                'bn_name' => 'KLPE-37',
                'status' => 'Active',
                'created_by' => 2,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2021-09-09 17:44:14',
                'updated_at' => '2021-09-09 17:44:14',
                'deleted_at' => NULL,
            ),
            45 => 
            array (
                'id' => 46,
                'brand_id' => 5,
            'name' => 'C80(SD-33)',
            'bn_name' => 'C80(SD-33)',
                'status' => 'Active',
                'created_by' => 2,
                'updated_by' => 2,
                'deleted_by' => NULL,
                'created_at' => '2021-09-09 17:44:51',
                'updated_at' => '2021-09-15 19:55:03',
                'deleted_at' => NULL,
            ),
            46 => 
            array (
                'id' => 47,
                'brand_id' => 14,
                'name' => 'TIPR-4213',
                'bn_name' => 'TIPR-4213',
                'status' => 'Active',
                'created_by' => 2,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2021-09-09 17:45:34',
                'updated_at' => '2021-09-09 17:45:34',
                'deleted_at' => NULL,
            ),
            47 => 
            array (
                'id' => 48,
                'brand_id' => 19,
                'name' => 'HW-43',
                'bn_name' => 'HW-43',
                'status' => 'Active',
                'created_by' => 2,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2021-09-09 17:46:21',
                'updated_at' => '2021-09-09 17:46:21',
                'deleted_at' => NULL,
            ),
            48 => 
            array (
                'id' => 49,
                'brand_id' => 1,
                'name' => 'FU313P',
                'bn_name' => 'FU313P',
                'status' => 'Active',
                'created_by' => 2,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2021-09-09 17:48:35',
                'updated_at' => '2021-09-09 17:48:35',
                'deleted_at' => NULL,
            ),
            49 => 
            array (
                'id' => 50,
                'brand_id' => 1,
                'name' => 'FK117HHR',
                'bn_name' => 'FK117HHR',
                'status' => 'Active',
                'created_by' => 2,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2021-09-09 17:52:05',
                'updated_at' => '2021-09-09 17:52:05',
                'deleted_at' => NULL,
            ),
            50 => 
            array (
                'id' => 51,
                'brand_id' => 1,
                'name' => 'FB-511',
                'bn_name' => 'FB-511',
                'status' => 'Active',
                'created_by' => 2,
                'updated_by' => NULL,
                'deleted_by' => 2,
                'created_at' => '2021-09-09 17:52:26',
                'updated_at' => '2021-09-09 19:35:38',
                'deleted_at' => '2021-09-09 19:35:38',
            ),
            51 => 
            array (
                'id' => 52,
                'brand_id' => 28,
                'name' => '2274',
                'bn_name' => '2274',
                'status' => 'Active',
                'created_by' => 2,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2021-09-09 17:53:29',
                'updated_at' => '2021-09-09 17:53:29',
                'deleted_at' => NULL,
            ),
            52 => 
            array (
                'id' => 53,
                'brand_id' => 28,
                'name' => 'LW-2275',
                'bn_name' => 'LW-2275',
                'status' => 'Active',
                'created_by' => 2,
                'updated_by' => 2,
                'deleted_by' => NULL,
                'created_at' => '2021-09-09 17:58:38',
                'updated_at' => '2021-09-12 20:28:23',
                'deleted_at' => NULL,
            ),
            53 => 
            array (
                'id' => 54,
                'brand_id' => 5,
                'name' => 'NISSAN 33',
                'bn_name' => 'NISSAN 33',
                'status' => 'Active',
                'created_by' => 2,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2021-09-09 18:06:45',
                'updated_at' => '2021-09-09 18:06:45',
                'deleted_at' => NULL,
            ),
            54 => 
            array (
                'id' => 55,
                'brand_id' => 1,
                'name' => 'FK6017 HHR',
                'bn_name' => 'FK6017 HHR',
                'status' => 'Active',
                'created_by' => 2,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2021-09-09 18:09:12',
                'updated_at' => '2021-09-09 18:09:12',
                'deleted_at' => NULL,
            ),
            55 => 
            array (
                'id' => 56,
                'brand_id' => 1,
                'name' => 'CTV NH-30',
                'bn_name' => 'CTV NH-30',
                'status' => 'Active',
                'created_by' => 2,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2021-09-09 18:09:50',
                'updated_at' => '2021-09-09 18:09:50',
                'deleted_at' => NULL,
            ),
            56 => 
            array (
                'id' => 57,
                'brand_id' => 1,
                'name' => 'CANTER FB-511',
                'bn_name' => 'CANTER FB-511',
                'status' => 'Active',
                'created_by' => 2,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2021-09-09 18:10:14',
                'updated_at' => '2021-09-09 18:10:14',
                'deleted_at' => NULL,
            ),
            57 => 
            array (
                'id' => 58,
                'brand_id' => 12,
                'name' => 'P-572',
                'bn_name' => 'P-572',
                'status' => 'Active',
                'created_by' => 2,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2021-09-09 18:20:45',
                'updated_at' => '2021-09-09 18:20:45',
                'deleted_at' => NULL,
            ),
            58 => 
            array (
                'id' => 59,
                'brand_id' => 21,
                'name' => 'B-2500',
                'bn_name' => 'B-2500',
                'status' => 'Active',
                'created_by' => 2,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2021-09-09 18:21:46',
                'updated_at' => '2021-09-09 18:21:46',
                'deleted_at' => NULL,
            ),
            59 => 
            array (
                'id' => 60,
                'brand_id' => 10,
            'name' => 'SD-33(12V)',
            'bn_name' => 'SD-33(12V)',
                'status' => 'Active',
                'created_by' => 2,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2021-09-09 18:22:11',
                'updated_at' => '2021-09-09 18:22:11',
                'deleted_at' => NULL,
            ),
            60 => 
            array (
                'id' => 61,
                'brand_id' => 2,
                'name' => 'E-2000',
                'bn_name' => 'E-2000',
                'status' => 'Active',
                'created_by' => 2,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2021-09-09 18:23:09',
                'updated_at' => '2021-09-09 18:23:09',
                'deleted_at' => NULL,
            ),
            61 => 
            array (
                'id' => 62,
                'brand_id' => 1,
                'name' => 'FK-617H',
                'bn_name' => 'FK-617H',
                'status' => 'Active',
                'created_by' => 2,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2021-09-09 18:25:04',
                'updated_at' => '2021-09-09 18:25:04',
                'deleted_at' => NULL,
            ),
            62 => 
            array (
                'id' => 63,
                'brand_id' => 2,
                'name' => 'NPC55F',
                'bn_name' => 'NPC55F',
                'status' => 'Active',
                'created_by' => 2,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2021-09-09 18:26:55',
                'updated_at' => '2021-09-09 18:26:55',
                'deleted_at' => NULL,
            ),
            63 => 
            array (
                'id' => 64,
                'brand_id' => 1,
                'name' => 'DA600619',
                'bn_name' => 'DA600619',
                'status' => 'Active',
                'created_by' => 2,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2021-09-09 18:27:31',
                'updated_at' => '2021-09-09 18:27:31',
                'deleted_at' => NULL,
            ),
            64 => 
            array (
                'id' => 65,
                'brand_id' => 1,
                'name' => 'FU-434',
                'bn_name' => 'FU-434',
                'status' => 'Active',
                'created_by' => 2,
                'updated_by' => 2,
                'deleted_by' => NULL,
                'created_at' => '2021-09-09 18:28:18',
                'updated_at' => '2021-09-12 17:13:53',
                'deleted_at' => NULL,
            ),
            65 => 
            array (
                'id' => 66,
                'brand_id' => 2,
                'name' => 'NPR 66G',
                'bn_name' => 'NPR 66G',
                'status' => 'Active',
                'created_by' => 2,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2021-09-09 18:30:06',
                'updated_at' => '2021-09-09 18:30:06',
                'deleted_at' => NULL,
            ),
            66 => 
            array (
                'id' => 67,
                'brand_id' => 16,
                'name' => 'KF-523',
                'bn_name' => 'KF-523',
                'status' => 'Active',
                'created_by' => 2,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2021-09-09 18:31:33',
                'updated_at' => '2021-09-09 18:31:33',
                'deleted_at' => NULL,
            ),
            67 => 
            array (
                'id' => 68,
                'brand_id' => 3,
                'name' => 'FK617HH',
                'bn_name' => 'FK617HH',
                'status' => 'Active',
                'created_by' => 2,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2021-09-09 18:32:15',
                'updated_at' => '2021-09-09 18:32:15',
                'deleted_at' => NULL,
            ),
            68 => 
            array (
                'id' => 69,
                'brand_id' => 5,
            'name' => 'FU-434(N)',
            'bn_name' => 'FU-434(N)',
                'status' => 'Active',
                'created_by' => 2,
                'updated_by' => NULL,
                'deleted_by' => 2,
                'created_at' => '2021-09-09 18:34:20',
                'updated_at' => '2021-09-12 17:12:51',
                'deleted_at' => '2021-09-12 17:12:51',
            ),
            69 => 
            array (
                'id' => 70,
                'brand_id' => 9,
                'name' => 'HKL-5030JHC',
                'bn_name' => 'HKL-5030JHC',
                'status' => 'Active',
                'created_by' => 2,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2021-09-09 18:35:16',
                'updated_at' => '2021-09-09 18:35:16',
                'deleted_at' => NULL,
            ),
            70 => 
            array (
                'id' => 71,
                'brand_id' => 14,
            'name' => 'CRUX(5KA)',
            'bn_name' => 'CRUX(5KA)',
                'status' => 'Active',
                'created_by' => 2,
                'updated_by' => 2,
                'deleted_by' => NULL,
                'created_at' => '2021-09-09 18:36:02',
                'updated_at' => '2021-09-16 16:20:20',
                'deleted_at' => NULL,
            ),
            71 => 
            array (
                'id' => 72,
                'brand_id' => 19,
                'name' => 'WUBN2ZRHAMRB3',
                'bn_name' => 'WUBN2ZRHAMRB3',
                'status' => 'Active',
                'created_by' => 2,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2021-09-09 18:37:16',
                'updated_at' => '2021-09-09 18:37:16',
                'deleted_at' => NULL,
            ),
            72 => 
            array (
                'id' => 73,
                'brand_id' => 6,
                'name' => 'LH202R-REMDE',
                'bn_name' => 'LH202R-REMDE',
                'status' => 'Active',
                'created_by' => 2,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2021-09-09 18:38:06',
                'updated_at' => '2021-09-09 18:38:06',
                'deleted_at' => NULL,
            ),
            73 => 
            array (
                'id' => 74,
                'brand_id' => 2,
                'name' => 'NP05SCAJ/JJ',
                'bn_name' => 'NP05SCAJ/JJ',
                'status' => 'Active',
                'created_by' => 2,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2021-09-09 18:39:42',
                'updated_at' => '2021-09-09 18:39:42',
                'deleted_at' => NULL,
            ),
            74 => 
            array (
                'id' => 75,
                'brand_id' => 1,
                'name' => 'K-34-TUNSR/L200',
                'bn_name' => 'K-34-TUNSR/L200',
                'status' => 'Active',
                'created_by' => 2,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2021-09-09 18:41:52',
                'updated_at' => '2021-09-09 18:41:52',
                'deleted_at' => NULL,
            ),
            75 => 
            array (
                'id' => 76,
                'brand_id' => 24,
                'name' => 'SPG6500E2',
                'bn_name' => 'SPG6500E2',
                'status' => 'Active',
                'created_by' => 2,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2021-09-09 18:43:02',
                'updated_at' => '2021-09-09 18:43:02',
                'deleted_at' => NULL,
            ),
            76 => 
            array (
                'id' => 77,
                'brand_id' => 23,
                'name' => 'SSH7600EX-KNS',
                'bn_name' => 'SSH7600EX-KNS',
                'status' => 'Active',
                'created_by' => 2,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2021-09-09 18:44:01',
                'updated_at' => '2021-09-09 18:44:01',
                'deleted_at' => NULL,
            ),
            77 => 
            array (
                'id' => 78,
                'brand_id' => 2,
                'name' => 'NFRSWN',
                'bn_name' => 'NFRSWN',
                'status' => 'Active',
                'created_by' => 2,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2021-09-09 18:44:41',
                'updated_at' => '2021-09-09 18:44:41',
                'deleted_at' => NULL,
            ),
            78 => 
            array (
                'id' => 79,
                'brand_id' => 2,
                'name' => '02F03',
                'bn_name' => '02F03',
                'status' => 'Active',
                'created_by' => 2,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2021-09-09 19:11:55',
                'updated_at' => '2021-09-09 19:11:55',
                'deleted_at' => NULL,
            ),
            79 => 
            array (
                'id' => 80,
                'brand_id' => 1,
                'name' => 'LOSD4RIER',
                'bn_name' => 'LOSD4RIER',
                'status' => 'Active',
                'created_by' => 2,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2021-09-09 19:12:57',
                'updated_at' => '2021-09-09 19:12:57',
                'deleted_at' => NULL,
            ),
            80 => 
            array (
                'id' => 81,
                'brand_id' => 2,
                'name' => 'D-MAX',
                'bn_name' => 'D-MAX',
                'status' => 'Active',
                'created_by' => 2,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2021-09-09 19:15:45',
                'updated_at' => '2021-09-09 19:15:45',
                'deleted_at' => NULL,
            ),
            81 => 
            array (
                'id' => 82,
                'brand_id' => 2,
                'name' => 'NPR71UHI5VAY',
                'bn_name' => 'NPR71UHI5VAY',
                'status' => 'Active',
                'created_by' => 2,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2021-09-09 19:18:06',
                'updated_at' => '2021-09-09 19:18:06',
                'deleted_at' => NULL,
            ),
            82 => 
            array (
                'id' => 83,
                'brand_id' => 2,
                'name' => 'TFS5Y20H2',
                'bn_name' => 'TFS5Y20H2',
                'status' => 'Active',
                'created_by' => 2,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2021-09-09 19:18:48',
                'updated_at' => '2021-09-09 19:18:48',
                'deleted_at' => NULL,
            ),
            83 => 
            array (
                'id' => 84,
                'brand_id' => 22,
                'name' => '1.4FIRE9GFMP8V',
                'bn_name' => '1.4FIRE9GFMP8V',
                'status' => 'Active',
                'created_by' => 2,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2021-09-09 19:19:50',
                'updated_at' => '2021-09-09 19:19:50',
                'deleted_at' => NULL,
            ),
            84 => 
            array (
                'id' => 85,
                'brand_id' => 11,
                'name' => 'VC52Q8',
                'bn_name' => 'VC52Q8',
                'status' => 'Active',
                'created_by' => 2,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2021-09-09 19:20:37',
                'updated_at' => '2021-09-09 19:20:37',
                'deleted_at' => NULL,
            ),
            85 => 
            array (
                'id' => 86,
                'brand_id' => 30,
                'name' => 'J112',
                'bn_name' => 'J112',
                'status' => 'Active',
                'created_by' => 2,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2021-09-09 19:23:56',
                'updated_at' => '2021-09-09 19:23:56',
                'deleted_at' => NULL,
            ),
            86 => 
            array (
                'id' => 87,
                'brand_id' => 2,
                'name' => 'NPR5SNAG/AS',
                'bn_name' => 'NPR5SNAG/AS',
                'status' => 'Active',
                'created_by' => 2,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2021-09-09 19:28:04',
                'updated_at' => '2021-09-09 19:28:04',
                'deleted_at' => NULL,
            ),
            87 => 
            array (
                'id' => 88,
                'brand_id' => 2,
                'name' => 'NPR-71J',
                'bn_name' => 'NPR-71J',
                'status' => 'Active',
                'created_by' => 2,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2021-09-09 19:29:00',
                'updated_at' => '2021-09-09 19:29:00',
                'deleted_at' => NULL,
            ),
            88 => 
            array (
                'id' => 89,
                'brand_id' => 11,
                'name' => 'VC4LASE',
                'bn_name' => 'VC4LASE',
                'status' => 'Active',
                'created_by' => 2,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2021-09-09 19:29:42',
                'updated_at' => '2021-09-09 19:29:42',
                'deleted_at' => NULL,
            ),
            89 => 
            array (
                'id' => 90,
                'brand_id' => 2,
                'name' => 'FIR-33H',
                'bn_name' => 'FIR-33H',
                'status' => 'Active',
                'created_by' => 2,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2021-09-09 19:31:02',
                'updated_at' => '2021-09-09 19:31:02',
                'deleted_at' => NULL,
            ),
            90 => 
            array (
                'id' => 91,
                'brand_id' => 10,
                'name' => 'BT-2037YMDV',
                'bn_name' => 'BT-2037YMDV',
                'status' => 'Active',
                'created_by' => 2,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2021-09-09 19:36:42',
                'updated_at' => '2021-09-09 19:36:42',
                'deleted_at' => NULL,
            ),
            91 => 
            array (
                'id' => 92,
                'brand_id' => 2,
                'name' => 'TKAJHOEK315',
                'bn_name' => 'TKAJHOEK315',
                'status' => 'Active',
                'created_by' => 2,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2021-09-09 19:41:45',
                'updated_at' => '2021-09-09 19:41:45',
                'deleted_at' => NULL,
            ),
            92 => 
            array (
                'id' => 93,
                'brand_id' => 2,
                'name' => 'NPR71H23',
                'bn_name' => 'NPR71H23',
                'status' => 'Active',
                'created_by' => 2,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2021-09-09 19:42:58',
                'updated_at' => '2021-09-09 19:42:58',
                'deleted_at' => NULL,
            ),
            93 => 
            array (
                'id' => 94,
                'brand_id' => 1,
                'name' => 'FE649C',
                'bn_name' => 'FE649C',
                'status' => 'Active',
                'created_by' => 2,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2021-09-09 19:43:43',
                'updated_at' => '2021-09-09 19:43:43',
                'deleted_at' => NULL,
            ),
            94 => 
            array (
                'id' => 95,
                'brand_id' => 21,
                'name' => 'E2500',
                'bn_name' => 'E2500',
                'status' => 'Active',
                'created_by' => 2,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2021-09-09 19:44:41',
                'updated_at' => '2021-09-09 19:44:41',
                'deleted_at' => NULL,
            ),
            95 => 
            array (
                'id' => 96,
                'brand_id' => 28,
                'name' => 'LW-2200',
                'bn_name' => 'LW-2200',
                'status' => 'Active',
                'created_by' => 2,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2021-09-09 19:47:53',
                'updated_at' => '2021-09-09 19:47:53',
                'deleted_at' => NULL,
            ),
            96 => 
            array (
                'id' => 97,
                'brand_id' => 5,
                'name' => 'FD-35',
                'bn_name' => 'FD-35',
                'status' => 'Active',
                'created_by' => 2,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2021-09-09 19:49:22',
                'updated_at' => '2021-09-09 19:49:22',
                'deleted_at' => NULL,
            ),
            97 => 
            array (
                'id' => 98,
                'brand_id' => 3,
                'name' => 'FK617H-A45052',
                'bn_name' => 'FK617H-A45052',
                'status' => 'Active',
                'created_by' => 2,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2021-09-09 19:52:31',
                'updated_at' => '2021-09-09 19:52:31',
                'deleted_at' => NULL,
            ),
            98 => 
            array (
                'id' => 99,
                'brand_id' => 2,
                'name' => 'JALFTR33H H7000031',
                'bn_name' => 'JALFTR33H H7000031',
                'status' => 'Active',
                'created_by' => 2,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2021-09-09 19:52:42',
                'updated_at' => '2021-09-09 19:52:42',
                'deleted_at' => NULL,
            ),
            99 => 
            array (
                'id' => 100,
                'brand_id' => 1,
                'name' => 'CANTER T-200C',
                'bn_name' => 'CANTER T-200C',
                'status' => 'Active',
                'created_by' => 2,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2021-09-09 19:54:39',
                'updated_at' => '2021-09-09 19:54:39',
                'deleted_at' => NULL,
            ),
            100 => 
            array (
                'id' => 101,
                'brand_id' => 2,
                'name' => 'IGR7035',
                'bn_name' => 'IGR7035',
                'status' => 'Active',
                'created_by' => 2,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2021-09-09 19:55:35',
                'updated_at' => '2021-09-09 19:55:35',
                'deleted_at' => NULL,
            ),
            101 => 
            array (
                'id' => 102,
                'brand_id' => 1,
                'name' => 'K8603T',
                'bn_name' => 'K8603T',
                'status' => 'Active',
                'created_by' => 2,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2021-09-09 19:56:56',
                'updated_at' => '2021-09-09 19:56:56',
                'deleted_at' => NULL,
            ),
            102 => 
            array (
                'id' => 103,
                'brand_id' => 2,
                'name' => '6197415',
                'bn_name' => '6197415',
                'status' => 'Active',
                'created_by' => 2,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2021-09-09 19:57:52',
                'updated_at' => '2021-09-09 19:57:52',
                'deleted_at' => NULL,
            ),
            103 => 
            array (
                'id' => 104,
                'brand_id' => 9,
                'name' => 'BTD-3524',
                'bn_name' => 'BTD-3524',
                'status' => 'Active',
                'created_by' => 2,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2021-09-09 19:58:31',
                'updated_at' => '2021-09-09 19:58:31',
                'deleted_at' => NULL,
            ),
            104 => 
            array (
                'id' => 105,
                'brand_id' => 2,
                'name' => 'TK-AHOEK-315',
                'bn_name' => 'TK-AHOEK-315',
                'status' => 'Active',
                'created_by' => 2,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2021-09-09 19:59:08',
                'updated_at' => '2021-09-09 19:59:08',
                'deleted_at' => NULL,
            ),
            105 => 
            array (
                'id' => 106,
                'brand_id' => 19,
                'name' => 'RAFTWU422RHKMRB3',
                'bn_name' => 'RAFTWU422RHKMRB3',
                'status' => 'Active',
                'created_by' => 2,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2021-09-09 20:02:21',
                'updated_at' => '2021-09-09 20:02:21',
                'deleted_at' => NULL,
            ),
            106 => 
            array (
                'id' => 107,
                'brand_id' => 2,
                'name' => 'NPR71HRD',
                'bn_name' => 'NPR71HRD',
                'status' => 'Active',
                'created_by' => 2,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2021-09-09 20:04:31',
                'updated_at' => '2021-09-09 20:04:31',
                'deleted_at' => NULL,
            ),
            107 => 
            array (
                'id' => 108,
                'brand_id' => 2,
                'name' => 'NPR/NQRT1870891',
                'bn_name' => 'NPR/NQRT1870891',
                'status' => 'Active',
                'created_by' => 2,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2021-09-09 20:06:48',
                'updated_at' => '2021-09-09 20:06:48',
                'deleted_at' => NULL,
            ),
            108 => 
            array (
                'id' => 109,
                'brand_id' => 2,
                'name' => 'ECENO-16',
                'bn_name' => 'ECENO-16',
                'status' => 'Active',
                'created_by' => 2,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2021-09-09 20:07:10',
                'updated_at' => '2021-09-09 20:07:10',
                'deleted_at' => NULL,
            ),
            109 => 
            array (
                'id' => 110,
                'brand_id' => 2,
                'name' => 'TFS-85',
                'bn_name' => 'TFS-85',
                'status' => 'Active',
                'created_by' => 2,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2021-09-09 20:07:39',
                'updated_at' => '2021-09-09 20:07:39',
                'deleted_at' => NULL,
            ),
            110 => 
            array (
                'id' => 111,
                'brand_id' => 29,
                'name' => 'D164360/2',
                'bn_name' => 'D164360/2',
                'status' => 'Active',
                'created_by' => 2,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2021-09-09 20:09:20',
                'updated_at' => '2021-09-09 20:09:20',
                'deleted_at' => NULL,
            ),
            111 => 
            array (
                'id' => 112,
                'brand_id' => 22,
                'name' => 'FLAT FIRE1368 MPI',
                'bn_name' => 'FLAT FIRE1368 MPI',
                'status' => 'Active',
                'created_by' => 2,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2021-09-09 20:10:37',
                'updated_at' => '2021-09-09 20:10:37',
                'deleted_at' => NULL,
            ),
            112 => 
            array (
                'id' => 113,
                'brand_id' => 2,
                'name' => 'NPR71H',
                'bn_name' => 'NPR71H',
                'status' => 'Active',
                'created_by' => 2,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2021-09-09 20:14:01',
                'updated_at' => '2021-09-09 20:14:01',
                'deleted_at' => NULL,
            ),
            113 => 
            array (
                'id' => 114,
                'brand_id' => 2,
                'name' => 'MD-NPR5SN',
                'bn_name' => 'MD-NPR5SN',
                'status' => 'Active',
                'created_by' => 2,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2021-09-09 20:15:14',
                'updated_at' => '2021-09-09 20:15:14',
                'deleted_at' => NULL,
            ),
            114 => 
            array (
                'id' => 115,
                'brand_id' => 19,
                'name' => 'TLF-KM-40/20',
                'bn_name' => 'TLF-KM-40/20',
                'status' => 'Active',
                'created_by' => 2,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2021-09-09 20:33:52',
                'updated_at' => '2021-09-09 20:33:52',
                'deleted_at' => NULL,
            ),
            115 => 
            array (
                'id' => 116,
                'brand_id' => 19,
                'name' => 'W4422R',
                'bn_name' => 'W4422R',
                'status' => 'Active',
                'created_by' => 2,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2021-09-09 20:34:54',
                'updated_at' => '2021-09-09 20:34:54',
                'deleted_at' => NULL,
            ),
            116 => 
            array (
                'id' => 117,
                'brand_id' => 2,
            'name' => 'FU-434(I)',
            'bn_name' => 'FU-434(I)',
                'status' => 'Active',
                'created_by' => 2,
                'updated_by' => NULL,
                'deleted_by' => 2,
                'created_at' => '2021-09-09 20:36:25',
                'updated_at' => '2021-09-12 17:12:56',
                'deleted_at' => '2021-09-12 17:12:56',
            ),
            117 => 
            array (
                'id' => 118,
                'brand_id' => 2,
                'name' => 'NPR-66',
                'bn_name' => 'NPR-66',
                'status' => 'Active',
                'created_by' => 2,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2021-09-09 20:37:17',
                'updated_at' => '2021-09-09 20:37:17',
                'deleted_at' => NULL,
            ),
            118 => 
            array (
                'id' => 119,
                'brand_id' => 10,
                'name' => 'LVAV2MBBXEJO',
                'bn_name' => 'LVAV2MBBXEJO',
                'status' => 'Active',
                'created_by' => 2,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2021-09-09 20:56:26',
                'updated_at' => '2021-09-09 20:56:26',
                'deleted_at' => NULL,
            ),
            119 => 
            array (
                'id' => 120,
                'brand_id' => 10,
                'name' => 'BY2037Y 3MDY',
                'bn_name' => 'BY2037Y 3MDY',
                'status' => 'Active',
                'created_by' => 2,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2021-09-09 20:58:36',
                'updated_at' => '2021-09-09 20:58:36',
                'deleted_at' => NULL,
            ),
            120 => 
            array (
                'id' => 121,
                'brand_id' => 1,
                'name' => 'L-300',
                'bn_name' => 'L-300',
                'status' => 'Active',
                'created_by' => 2,
                'updated_by' => 2,
                'deleted_by' => NULL,
                'created_at' => '2021-09-09 20:59:57',
                'updated_at' => '2021-09-12 19:44:55',
                'deleted_at' => NULL,
            ),
            121 => 
            array (
                'id' => 122,
                'brand_id' => 2,
                'name' => '4JJTCXMUXSS',
                'bn_name' => '4JJTCXMUXSS',
                'status' => 'Active',
                'created_by' => 2,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2021-09-09 21:08:50',
                'updated_at' => '2021-09-09 21:08:50',
                'deleted_at' => NULL,
            ),
            122 => 
            array (
                'id' => 123,
                'brand_id' => 1,
                'name' => 'FB5',
                'bn_name' => 'FB5',
                'status' => 'Active',
                'created_by' => 2,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2021-09-09 21:09:23',
                'updated_at' => '2021-09-09 21:09:23',
                'deleted_at' => NULL,
            ),
            123 => 
            array (
                'id' => 124,
                'brand_id' => 2,
                'name' => 'FS54HBH',
                'bn_name' => 'FS54HBH',
                'status' => 'Active',
                'created_by' => 2,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2021-09-09 21:12:23',
                'updated_at' => '2021-09-09 21:12:23',
                'deleted_at' => NULL,
            ),
            124 => 
            array (
                'id' => 125,
                'brand_id' => 1,
                'name' => '4DR5',
                'bn_name' => '4DR5',
                'status' => 'Active',
                'created_by' => 2,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2021-09-12 14:19:04',
                'updated_at' => '2021-09-12 14:19:04',
                'deleted_at' => NULL,
            ),
            125 => 
            array (
                'id' => 126,
                'brand_id' => 6,
                'name' => '2LT',
                'bn_name' => '2LT',
                'status' => 'Active',
                'created_by' => 2,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2021-09-12 16:11:29',
                'updated_at' => '2021-09-12 16:11:29',
                'deleted_at' => NULL,
            ),
            126 => 
            array (
                'id' => 127,
                'brand_id' => 2,
                'name' => 'DA-640',
                'bn_name' => 'DA-640',
                'status' => 'Active',
                'created_by' => 2,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2021-09-12 16:12:47',
                'updated_at' => '2021-09-12 16:12:47',
                'deleted_at' => NULL,
            ),
            127 => 
            array (
                'id' => 128,
                'brand_id' => 6,
            'name' => 'HIACE(2LT)',
            'bn_name' => 'HIACE(2LT)',
                'status' => 'Active',
                'created_by' => 2,
                'updated_by' => 2,
                'deleted_by' => NULL,
                'created_at' => '2021-09-12 16:49:57',
                'updated_at' => '2021-09-15 20:24:45',
                'deleted_at' => NULL,
            ),
            128 => 
            array (
                'id' => 129,
                'brand_id' => 21,
                'name' => 'E-2200',
                'bn_name' => 'E-2200',
                'status' => 'Active',
                'created_by' => 2,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2021-09-12 17:03:27',
                'updated_at' => '2021-09-12 17:03:27',
                'deleted_at' => NULL,
            ),
            129 => 
            array (
                'id' => 130,
                'brand_id' => 33,
                'name' => 'QM250J-2L',
                'bn_name' => 'QM250J-2L',
                'status' => 'Active',
                'created_by' => 2,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2021-09-12 19:00:50',
                'updated_at' => '2021-09-12 19:00:50',
                'deleted_at' => NULL,
            ),
            130 => 
            array (
                'id' => 131,
                'brand_id' => 27,
                'name' => 'CD-100',
                'bn_name' => 'CD-100',
                'status' => 'Active',
                'created_by' => 2,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2021-09-12 19:32:46',
                'updated_at' => '2021-09-12 19:32:46',
                'deleted_at' => NULL,
            ),
            131 => 
            array (
                'id' => 132,
                'brand_id' => 5,
                'name' => 'SD-23',
                'bn_name' => 'SD-23',
                'status' => 'Active',
                'created_by' => 2,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2021-09-12 19:33:19',
                'updated_at' => '2021-09-12 19:33:19',
                'deleted_at' => NULL,
            ),
            132 => 
            array (
                'id' => 133,
                'brand_id' => 1,
                'name' => '4G64',
                'bn_name' => '4G64',
                'status' => 'Active',
                'created_by' => 2,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2021-09-12 19:34:08',
                'updated_at' => '2021-09-12 19:34:08',
                'deleted_at' => NULL,
            ),
            133 => 
            array (
                'id' => 134,
                'brand_id' => 32,
                'name' => 'P 572',
                'bn_name' => 'P 572',
                'status' => 'Active',
                'created_by' => 2,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2021-09-12 19:35:34',
                'updated_at' => '2021-09-12 19:35:34',
                'deleted_at' => NULL,
            ),
            134 => 
            array (
                'id' => 135,
                'brand_id' => 1,
                'name' => 'FK-115',
                'bn_name' => 'FK-115',
                'status' => 'Active',
                'created_by' => 2,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2021-09-12 19:43:26',
                'updated_at' => '2021-09-12 19:43:26',
                'deleted_at' => NULL,
            ),
            135 => 
            array (
                'id' => 136,
                'brand_id' => 6,
                'name' => '2J',
                'bn_name' => '2J',
                'status' => 'Active',
                'created_by' => 2,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2021-09-12 19:44:22',
                'updated_at' => '2021-09-12 19:44:22',
                'deleted_at' => NULL,
            ),
            136 => 
            array (
                'id' => 137,
                'brand_id' => 2,
                'name' => 'TFS54H',
                'bn_name' => 'TFS54H',
                'status' => 'Active',
                'created_by' => 2,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2021-09-13 18:03:21',
                'updated_at' => '2021-09-13 18:03:21',
                'deleted_at' => NULL,
            ),
            137 => 
            array (
                'id' => 138,
                'brand_id' => 22,
            'name' => '1000(FIAT 1242)',
            'bn_name' => '1000(FIAT 1242)',
                'status' => 'Active',
                'created_by' => 2,
                'updated_by' => 2,
                'deleted_by' => NULL,
                'created_at' => '2021-09-14 17:41:48',
                'updated_at' => '2021-09-15 19:12:34',
                'deleted_at' => NULL,
            ),
            138 => 
            array (
                'id' => 139,
                'brand_id' => 1,
                'name' => 'FM 617 HHR',
                'bn_name' => 'FM 617 HHR',
                'status' => 'Active',
                'created_by' => 2,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2021-09-14 19:09:44',
                'updated_at' => '2021-09-14 19:09:44',
                'deleted_at' => NULL,
            ),
            139 => 
            array (
                'id' => 140,
                'brand_id' => 1,
                'name' => '4G54',
                'bn_name' => '4G54',
                'status' => 'Active',
                'created_by' => 2,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2021-09-15 16:20:39',
                'updated_at' => '2021-09-15 16:20:39',
                'deleted_at' => NULL,
            ),
            140 => 
            array (
                'id' => 141,
                'brand_id' => 2,
                'name' => 'CAP TYPE TOWING',
                'bn_name' => 'ক্যাপ টাইপ টোয়িং',
                'status' => 'Active',
                'created_by' => 2,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2021-09-15 18:05:35',
                'updated_at' => '2021-09-15 18:05:35',
                'deleted_at' => NULL,
            ),
            141 => 
            array (
                'id' => 142,
                'brand_id' => 6,
            'name' => 'TOYOACE(2J)',
            'bn_name' => 'TOYOACE(2J)',
                'status' => 'Active',
                'created_by' => 2,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2021-09-15 20:12:17',
                'updated_at' => '2021-09-15 20:12:17',
                'deleted_at' => NULL,
            ),
            142 => 
            array (
                'id' => 143,
                'brand_id' => 2,
                'name' => 'FTR',
                'bn_name' => 'FTR',
                'status' => 'Active',
                'created_by' => 2,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2021-09-20 16:28:08',
                'updated_at' => '2021-09-20 16:28:08',
                'deleted_at' => NULL,
            ),
            143 => 
            array (
                'id' => 144,
                'brand_id' => 2,
                'name' => 'TIF-30',
                'bn_name' => 'TIF-30',
                'status' => 'Active',
                'created_by' => 2,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2021-09-20 16:59:53',
                'updated_at' => '2021-09-20 16:59:53',
                'deleted_at' => NULL,
            ),
            144 => 
            array (
                'id' => 145,
                'brand_id' => 10,
                'name' => 'BJ2037',
                'bn_name' => 'BJ2037',
                'status' => 'Active',
                'created_by' => 2,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2021-09-20 17:35:56',
                'updated_at' => '2021-09-20 17:35:56',
                'deleted_at' => NULL,
            ),
            145 => 
            array (
                'id' => 146,
                'brand_id' => 2,
                'name' => 'TKAHO-EK 57',
                'bn_name' => 'TKAHO-EK 57',
                'status' => 'Active',
                'created_by' => 2,
                'updated_by' => 2,
                'deleted_by' => NULL,
                'created_at' => '2021-09-21 16:31:29',
                'updated_at' => '2021-09-21 18:18:22',
                'deleted_at' => NULL,
            ),
        ));
        
        
    }
}